- platform: mqtt_room
  name: "Robins Apple Watch BLE"
  device_id: "irk:c93b50e50b6f669430636782425e412c"
  state_topic: "espresense/rooms"
  timeout: 5
  away_timeout: 60
- platform: mqtt_room
  name: "Wills Apple Watch BLE"
  device_id: "irk:a779107f6ff594d96af9abad824f1ae5"
  state_topic: "espresense/rooms"
  timeout: 5
  away_timeout: 60
- platform: mqtt_room
  name: "Wills iPhone BLE"
  device_id: "irk:461d38265373b3aa951972690bd78b42"
  state_topic: "espresense/rooms"
  timeout: 5
  away_timeout: 60